# M/L Commando Course, Cambridge 2018
## Neural Networks

We revisit our well-known Titanic data again, this time using Keras with Tensorflow to build Neural Network classifiers, for survival prediction (binary classification) and to estimate the class of a passenger (multiclass classification).

In [114]:
from math import exp
from random import random, shuffle, choice, randint
import pandas as pd
import numpy as np

from keras import Input
from numpy import array, mean
from pandas import concat
from pandas import DataFrame
from keras.models import Sequential
from keras.layers import Dense,Reshape

import matplotlib.pyplot as plt

In [110]:
titanic_raw = pd.read_csv('data/titanic.csv')
print (titanic_raw[12:14])

    row.names pclass  survived                          name  age  \
12         13    1st         1  Aubert, Mrs Leontine Pauline  NaN   
13         14    1st         1     Barkworth, Mr Algernon H.  NaN   

       embarked      home.dest  room        ticket boat     sex  
12    Cherbourg  Paris, France  B-35  17477 L69 6s    9  female  
13  Southampton  Hessle, Yorks  A-23           NaN    B    male  


In [111]:
from sklearn import feature_extraction
from sklearn.model_selection import train_test_split

def one_hot_dataframe(data, cols, replace=False):
    dic_vecr = feature_extraction.DictVectorizer()
    stuff_to_transform = data[cols]
    dty_list = stuff_to_transform.to_dict(orient='records') #rjm49 - this call makes a dict for each record in the table, returns them all as a list
    txd = dic_vecr.fit_transform(dty_list) #converts string types to 1-hot-encoded classes as a NumPy "sparse array"
    vecData = pd.DataFrame( txd.toarray())
    vecData.columns = dic_vecr.get_feature_names()
    vecData.index = data.index
    if replace is True: #replace the columns in data with those from our VecData object
        data = data.drop(cols, axis=1)
        data = data.join(vecData)
    return (data, vecData)

titanic, _ = one_hot_dataframe(titanic_raw, ['pclass', 'embarked', 'sex'], replace=True)
titanic_target = titanic['survived']

mean_age = titanic['age'].mean()
titanic['age'].fillna(mean_age, inplace=True)

titanic.fillna(0, inplace=True)

titanic_data = titanic.drop(['name', 'row.names', 'survived', 'embarked', 'home.dest','ticket','boat','room'], axis=1) #can use inplace=True to alter original

print(titanic_data.head())
X_train, X_test, y_train, y_test = train_test_split(titanic_data, titanic_target, test_size=0.25, random_state=42)


       age  embarked=Cherbourg  embarked=Queenstown  embarked=Southampton  \
0  29.0000                 0.0                  0.0                   1.0   
1   2.0000                 0.0                  0.0                   1.0   
2  30.0000                 0.0                  0.0                   1.0   
3  25.0000                 0.0                  0.0                   1.0   
4   0.9167                 0.0                  0.0                   1.0   

   pclass=1st  pclass=2nd  pclass=3rd  sex=female  sex=male  
0         1.0         0.0         0.0         1.0       0.0  
1         1.0         0.0         0.0         1.0       0.0  
2         1.0         0.0         0.0         0.0       1.0  
3         1.0         0.0         0.0         1.0       0.0  
4         1.0         0.0         0.0         0.0       1.0  


In [115]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(10, input_shape=(9,)),
    Activation('relu'),
    Dense(1),
    Activation('sigmoid'),
])

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["acc", "mse"])
model.fit(X_train, y_train, epochs=1000)

Epoch 1/1000
984/984 [==============================] - 0s 251us/step - loss: 3.9196 - acc: 0.3283 - mean_squared_error: 0.6581
Epoch 2/1000
984/984 [==============================] - 0s 46us/step - loss: 2.3542 - acc: 0.3232 - mean_squared_error: 0.6079
Epoch 3/1000
984/984 [==============================] - 0s 43us/step - loss: 1.1245 - acc: 0.3140 - mean_squared_error: 0.4128
Epoch 4/1000
984/984 [==============================] - 0s 51us/step - loss: 0.6794 - acc: 0.5823 - mean_squared_error: 0.2428
Epoch 5/1000
984/984 [==============================] - 0s 48us/step - loss: 0.6323 - acc: 0.6687 - mean_squared_error: 0.2202
Epoch 6/1000
984/984 [==============================] - 0s 49us/step - loss: 0.6235 - acc: 0.6687 - mean_squared_error: 0.2164
Epoch 7/1000
984/984 [==============================] - 0s 49us/step - loss: 0.6151 - acc: 0.6687 - mean_squared_error: 0.2126
Epoch 8/1000
984/984 [==============================] - 0s 47us/step - loss: 0.6075 - acc: 0.6687 - mean_squar

984/984 [==============================] - 0s 42us/step - loss: 0.4264 - acc: 0.8181 - mean_squared_error: 0.1331
Epoch 66/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4266 - acc: 0.8191 - mean_squared_error: 0.1329
Epoch 67/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4261 - acc: 0.8211 - mean_squared_error: 0.1327
Epoch 68/1000
984/984 [==============================] - 0s 40us/step - loss: 0.4262 - acc: 0.8161 - mean_squared_error: 0.1330
Epoch 69/1000
984/984 [==============================] - 0s 38us/step - loss: 0.4262 - acc: 0.8201 - mean_squared_error: 0.1328
Epoch 70/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4262 - acc: 0.8201 - mean_squared_error: 0.1328
Epoch 71/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4254 - acc: 0.8181 - mean_squared_error: 0.1326
Epoch 72/1000
984/984 [==============================] - 0s 41us/step - loss: 0.4251 - acc: 0.8201 - mean_squared_erro

984/984 [==============================] - 0s 59us/step - loss: 0.4233 - acc: 0.8191 - mean_squared_error: 0.1316
Epoch 129/1000
984/984 [==============================] - 0s 53us/step - loss: 0.4285 - acc: 0.8191 - mean_squared_error: 0.1339
Epoch 130/1000
984/984 [==============================] - 0s 63us/step - loss: 0.4241 - acc: 0.8191 - mean_squared_error: 0.1321
Epoch 131/1000
984/984 [==============================] - 0s 46us/step - loss: 0.4231 - acc: 0.8201 - mean_squared_error: 0.1318
Epoch 132/1000
984/984 [==============================] - 0s 45us/step - loss: 0.4236 - acc: 0.8211 - mean_squared_error: 0.1321
Epoch 133/1000
984/984 [==============================] - 0s 47us/step - loss: 0.4224 - acc: 0.8191 - mean_squared_error: 0.1314
Epoch 134/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4256 - acc: 0.8150 - mean_squared_error: 0.1327
Epoch 135/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4205 - acc: 0.8211 - mean_squar

984/984 [==============================] - 0s 41us/step - loss: 0.4144 - acc: 0.8283 - mean_squared_error: 0.1280
Epoch 192/1000
984/984 [==============================] - 0s 42us/step - loss: 0.4145 - acc: 0.8283 - mean_squared_error: 0.1279
Epoch 193/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4174 - acc: 0.8313 - mean_squared_error: 0.1292
Epoch 194/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4149 - acc: 0.8232 - mean_squared_error: 0.1282
Epoch 195/1000
984/984 [==============================] - 0s 49us/step - loss: 0.4154 - acc: 0.8303 - mean_squared_error: 0.1284
Epoch 196/1000
984/984 [==============================] - 0s 38us/step - loss: 0.4136 - acc: 0.8283 - mean_squared_error: 0.1277
Epoch 197/1000
984/984 [==============================] - 0s 55us/step - loss: 0.4122 - acc: 0.8293 - mean_squared_error: 0.1274
Epoch 198/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4130 - acc: 0.8272 - mean_squar

984/984 [==============================] - 0s 62us/step - loss: 0.4120 - acc: 0.8303 - mean_squared_error: 0.1276
Epoch 255/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4103 - acc: 0.8283 - mean_squared_error: 0.1264
Epoch 256/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4119 - acc: 0.8262 - mean_squared_error: 0.1275
Epoch 257/1000
984/984 [==============================] - 0s 49us/step - loss: 0.4120 - acc: 0.8303 - mean_squared_error: 0.1277
Epoch 258/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4103 - acc: 0.8283 - mean_squared_error: 0.1269
Epoch 259/1000
984/984 [==============================] - 0s 41us/step - loss: 0.4105 - acc: 0.8303 - mean_squared_error: 0.1270
Epoch 260/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4101 - acc: 0.8313 - mean_squared_error: 0.1268
Epoch 261/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4106 - acc: 0.8323 - mean_squar

984/984 [==============================] - 0s 41us/step - loss: 0.4102 - acc: 0.8272 - mean_squared_error: 0.1270
Epoch 318/1000
984/984 [==============================] - 0s 41us/step - loss: 0.4111 - acc: 0.8313 - mean_squared_error: 0.1273
Epoch 319/1000
984/984 [==============================] - 0s 45us/step - loss: 0.4090 - acc: 0.8283 - mean_squared_error: 0.1266
Epoch 320/1000
984/984 [==============================] - 0s 41us/step - loss: 0.4100 - acc: 0.8323 - mean_squared_error: 0.1266
Epoch 321/1000
984/984 [==============================] - 0s 50us/step - loss: 0.4098 - acc: 0.8283 - mean_squared_error: 0.1270
Epoch 322/1000
984/984 [==============================] - 0s 69us/step - loss: 0.4101 - acc: 0.8303 - mean_squared_error: 0.1268
Epoch 323/1000
984/984 [==============================] - 0s 63us/step - loss: 0.4101 - acc: 0.8303 - mean_squared_error: 0.1270
Epoch 324/1000
984/984 [==============================] - 0s 58us/step - loss: 0.4094 - acc: 0.8283 - mean_squar

984/984 [==============================] - 0s 63us/step - loss: 0.4100 - acc: 0.8283 - mean_squared_error: 0.1271
Epoch 381/1000
984/984 [==============================] - 0s 66us/step - loss: 0.4087 - acc: 0.8272 - mean_squared_error: 0.1265
Epoch 382/1000
984/984 [==============================] - 0s 41us/step - loss: 0.4096 - acc: 0.8293 - mean_squared_error: 0.1266
Epoch 383/1000
984/984 [==============================] - 0s 54us/step - loss: 0.4097 - acc: 0.8283 - mean_squared_error: 0.1267
Epoch 384/1000
984/984 [==============================] - 0s 63us/step - loss: 0.4118 - acc: 0.8333 - mean_squared_error: 0.1276
Epoch 385/1000
984/984 [==============================] - 0s 61us/step - loss: 0.4097 - acc: 0.8252 - mean_squared_error: 0.1272
Epoch 386/1000
984/984 [==============================] - 0s 63us/step - loss: 0.4091 - acc: 0.8303 - mean_squared_error: 0.1266
Epoch 387/1000
984/984 [==============================] - 0s 55us/step - loss: 0.4091 - acc: 0.8293 - mean_squar

984/984 [==============================] - 0s 43us/step - loss: 0.4089 - acc: 0.8272 - mean_squared_error: 0.1266
Epoch 444/1000
984/984 [==============================] - 0s 46us/step - loss: 0.4093 - acc: 0.8283 - mean_squared_error: 0.1269
Epoch 445/1000
984/984 [==============================] - 0s 42us/step - loss: 0.4103 - acc: 0.8272 - mean_squared_error: 0.1271
Epoch 446/1000
984/984 [==============================] - 0s 48us/step - loss: 0.4092 - acc: 0.8303 - mean_squared_error: 0.1268
Epoch 447/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4090 - acc: 0.8283 - mean_squared_error: 0.1266
Epoch 448/1000
984/984 [==============================] - 0s 42us/step - loss: 0.4084 - acc: 0.8272 - mean_squared_error: 0.1264
Epoch 449/1000
984/984 [==============================] - 0s 42us/step - loss: 0.4106 - acc: 0.8303 - mean_squared_error: 0.1274
Epoch 450/1000
984/984 [==============================] - 0s 38us/step - loss: 0.4096 - acc: 0.8313 - mean_squar

984/984 [==============================] - 0s 79us/step - loss: 0.4088 - acc: 0.8333 - mean_squared_error: 0.1262
Epoch 507/1000
984/984 [==============================] - 0s 78us/step - loss: 0.4122 - acc: 0.8283 - mean_squared_error: 0.1284
Epoch 508/1000
984/984 [==============================] - 0s 59us/step - loss: 0.4094 - acc: 0.8313 - mean_squared_error: 0.1269
Epoch 509/1000
984/984 [==============================] - 0s 43us/step - loss: 0.4086 - acc: 0.8283 - mean_squared_error: 0.1266
Epoch 510/1000
984/984 [==============================] - 0s 56us/step - loss: 0.4118 - acc: 0.8313 - mean_squared_error: 0.1277
Epoch 511/1000
984/984 [==============================] - 0s 45us/step - loss: 0.4087 - acc: 0.8272 - mean_squared_error: 0.1264
Epoch 512/1000
984/984 [==============================] - 0s 45us/step - loss: 0.4090 - acc: 0.8293 - mean_squared_error: 0.1266
Epoch 513/1000
984/984 [==============================] - 0s 63us/step - loss: 0.4088 - acc: 0.8262 - mean_squar

984/984 [==============================] - 0s 79us/step - loss: 0.4083 - acc: 0.8293 - mean_squared_error: 0.1265
Epoch 570/1000
984/984 [==============================] - 0s 52us/step - loss: 0.4107 - acc: 0.8323 - mean_squared_error: 0.1271
Epoch 571/1000
984/984 [==============================] - 0s 42us/step - loss: 0.4103 - acc: 0.8252 - mean_squared_error: 0.1272
Epoch 572/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4095 - acc: 0.8293 - mean_squared_error: 0.1269
Epoch 573/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4085 - acc: 0.8262 - mean_squared_error: 0.1265
Epoch 574/1000
984/984 [==============================] - 0s 38us/step - loss: 0.4093 - acc: 0.8283 - mean_squared_error: 0.1267
Epoch 575/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4139 - acc: 0.8283 - mean_squared_error: 0.1280
Epoch 576/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4105 - acc: 0.8303 - mean_squar

984/984 [==============================] - 0s 33us/step - loss: 0.4085 - acc: 0.8262 - mean_squared_error: 0.1264
Epoch 633/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4082 - acc: 0.8283 - mean_squared_error: 0.1263
Epoch 634/1000
984/984 [==============================] - 0s 31us/step - loss: 0.4084 - acc: 0.8293 - mean_squared_error: 0.1265
Epoch 635/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4078 - acc: 0.8272 - mean_squared_error: 0.1263
Epoch 636/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4095 - acc: 0.8283 - mean_squared_error: 0.1268
Epoch 637/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4097 - acc: 0.8262 - mean_squared_error: 0.1269
Epoch 638/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4102 - acc: 0.8343 - mean_squared_error: 0.1268
Epoch 639/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4076 - acc: 0.8303 - mean_squar

984/984 [==============================] - 0s 32us/step - loss: 0.4107 - acc: 0.8283 - mean_squared_error: 0.1274
Epoch 696/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4079 - acc: 0.8323 - mean_squared_error: 0.1262
Epoch 697/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4082 - acc: 0.8293 - mean_squared_error: 0.1266
Epoch 698/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4113 - acc: 0.8293 - mean_squared_error: 0.1276
Epoch 699/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4082 - acc: 0.8293 - mean_squared_error: 0.1265
Epoch 700/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4081 - acc: 0.8252 - mean_squared_error: 0.1264
Epoch 701/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4097 - acc: 0.8252 - mean_squared_error: 0.1269
Epoch 702/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4082 - acc: 0.8283 - mean_squar

984/984 [==============================] - 0s 33us/step - loss: 0.4085 - acc: 0.8293 - mean_squared_error: 0.1264
Epoch 759/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4099 - acc: 0.8262 - mean_squared_error: 0.1271
Epoch 760/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4074 - acc: 0.8303 - mean_squared_error: 0.1263
Epoch 761/1000
984/984 [==============================] - 0s 34us/step - loss: 0.4088 - acc: 0.8323 - mean_squared_error: 0.1263
Epoch 762/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4080 - acc: 0.8303 - mean_squared_error: 0.1264
Epoch 763/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4077 - acc: 0.8262 - mean_squared_error: 0.1261
Epoch 764/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4096 - acc: 0.8272 - mean_squared_error: 0.1271
Epoch 765/1000
984/984 [==============================] - 0s 35us/step - loss: 0.4083 - acc: 0.8323 - mean_squar

984/984 [==============================] - 0s 32us/step - loss: 0.4089 - acc: 0.8293 - mean_squared_error: 0.1264
Epoch 822/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4080 - acc: 0.8283 - mean_squared_error: 0.1266
Epoch 823/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4096 - acc: 0.8293 - mean_squared_error: 0.1270
Epoch 824/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4076 - acc: 0.8283 - mean_squared_error: 0.1261
Epoch 825/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4084 - acc: 0.8262 - mean_squared_error: 0.1265
Epoch 826/1000
984/984 [==============================] - 0s 37us/step - loss: 0.4096 - acc: 0.8333 - mean_squared_error: 0.1269
Epoch 827/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4108 - acc: 0.8283 - mean_squared_error: 0.1277
Epoch 828/1000
984/984 [==============================] - 0s 34us/step - loss: 0.4079 - acc: 0.8283 - mean_squar

984/984 [==============================] - 0s 33us/step - loss: 0.4074 - acc: 0.8283 - mean_squared_error: 0.1262
Epoch 885/1000
984/984 [==============================] - 0s 39us/step - loss: 0.4080 - acc: 0.8293 - mean_squared_error: 0.1264
Epoch 886/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4081 - acc: 0.8293 - mean_squared_error: 0.1265
Epoch 887/1000
984/984 [==============================] - 0s 34us/step - loss: 0.4075 - acc: 0.8293 - mean_squared_error: 0.1261
Epoch 888/1000
984/984 [==============================] - 0s 35us/step - loss: 0.4091 - acc: 0.8313 - mean_squared_error: 0.1268
Epoch 889/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4091 - acc: 0.8283 - mean_squared_error: 0.1269
Epoch 890/1000
984/984 [==============================] - 0s 34us/step - loss: 0.4092 - acc: 0.8313 - mean_squared_error: 0.1267
Epoch 891/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4076 - acc: 0.8272 - mean_squar

984/984 [==============================] - 0s 33us/step - loss: 0.4079 - acc: 0.8272 - mean_squared_error: 0.1265
Epoch 948/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4079 - acc: 0.8283 - mean_squared_error: 0.1265
Epoch 949/1000
984/984 [==============================] - 0s 33us/step - loss: 0.4077 - acc: 0.8272 - mean_squared_error: 0.1261
Epoch 950/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4090 - acc: 0.8293 - mean_squared_error: 0.1268
Epoch 951/1000
984/984 [==============================] - 0s 40us/step - loss: 0.4083 - acc: 0.8293 - mean_squared_error: 0.1268
Epoch 952/1000
984/984 [==============================] - 0s 35us/step - loss: 0.4099 - acc: 0.8272 - mean_squared_error: 0.1268
Epoch 953/1000
984/984 [==============================] - 0s 32us/step - loss: 0.4075 - acc: 0.8283 - mean_squared_error: 0.1261
Epoch 954/1000
984/984 [==============================] - 0s 36us/step - loss: 0.4082 - acc: 0.8283 - mean_squar

In [32]:
score = model.evaluate(X_train, y_train)
print("train score: {}".format(score))
score = model.evaluate(X_test, y_test)
print("test score: {}".format(score))

984/984 [==============================] - 0s 26us/step
train score: [0.41978892393228484, 0.82723577235772361, 0.12977073377952342]
329/329 [==============================] - 0s 30us/step
test score: [0.46506229287585227, 0.8358662615793454, 0.13943409380760599]


## Multiclass classification
Next we take a look at a classification problem where the result is always exactly one of N classes.  This is called a multi-class problem.
(Do not confuse with a _multi-label_ problem, where we can have any number of labels (or none!) positive for a given datum.)

In our case we'll try to use the passenger's age, gender and embarkation point to determine the likely class of their ticket.

In [104]:
model = Sequential([
    Dense(5, input_shape=(6,)),
    Activation('relu'),
    Dense(3),
    Activation('softmax'),
])

titanic_class_target = titanic[["pclass=1st","pclass=2nd","pclass=3rd"]]
titanic_classless_data = titanic_data.drop(["pclass=1st","pclass=2nd","pclass=3rd"], axis=1)
X_train, X_test, y_train, y_test = train_test_split(titanic_classless_data, titanic_class_target, test_size=0.25, random_state=42)

print(X_train.head())

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["acc", "mse"])
history = model.fit(X_train, y_train, epochs=1000)

plt.plot(history.history['loss'])
plt.plot(history.history['acc'])
plt.plot(history.history['mse'])
plt.show()

            age  embarked=Cherbourg  embarked=Queenstown  \
88    50.000000                 1.0                  0.0   
1199  31.194181                 0.0                  0.0   
1097  31.194181                 0.0                  0.0   
1090  31.194181                 0.0                  0.0   
711   37.000000                 0.0                  1.0   

      embarked=Southampton  sex=female  sex=male  
88                     0.0         0.0       1.0  
1199                   0.0         0.0       1.0  
1097                   0.0         0.0       1.0  
1090                   0.0         1.0       0.0  
711                    0.0         1.0       0.0  
Epoch 1/1000
984/984 [==============================] - 0s 238us/step - loss: 5.7889 - acc: 0.2083 - mean_squared_error: 0.5182
Epoch 2/1000
984/984 [==============================] - 0s 45us/step - loss: 3.9687 - acc: 0.2083 - mean_squared_error: 0.4925
Epoch 3/1000
984/984 [==============================] - 0s 50us/step - loss: 2

984/984 [==============================] - 0s 38us/step - loss: 0.8449 - acc: 0.5986 - mean_squared_error: 0.1629
Epoch 60/1000
984/984 [==============================] - 0s 43us/step - loss: 0.8407 - acc: 0.6006 - mean_squared_error: 0.1621
Epoch 61/1000
984/984 [==============================] - 0s 50us/step - loss: 0.8371 - acc: 0.6067 - mean_squared_error: 0.1611
Epoch 62/1000
984/984 [==============================] - 0s 65us/step - loss: 0.8346 - acc: 0.6057 - mean_squared_error: 0.1605
Epoch 63/1000
984/984 [==============================] - 0s 63us/step - loss: 0.8323 - acc: 0.6077 - mean_squared_error: 0.1601
Epoch 64/1000
984/984 [==============================] - 0s 75us/step - loss: 0.8276 - acc: 0.6016 - mean_squared_error: 0.1590
Epoch 65/1000
984/984 [==============================] - 0s 84us/step - loss: 0.8237 - acc: 0.6067 - mean_squared_error: 0.1579
Epoch 66/1000
984/984 [==============================] - 0s 54us/step - loss: 0.8201 - acc: 0.6179 - mean_squared_erro

984/984 [==============================] - 0s 41us/step - loss: 0.6988 - acc: 0.6839 - mean_squared_error: 0.1321
Epoch 123/1000
984/984 [==============================] - 0s 43us/step - loss: 0.6962 - acc: 0.6850 - mean_squared_error: 0.1315
Epoch 124/1000
984/984 [==============================] - 0s 48us/step - loss: 0.6959 - acc: 0.6829 - mean_squared_error: 0.1315
Epoch 125/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6941 - acc: 0.6870 - mean_squared_error: 0.1312
Epoch 126/1000
984/984 [==============================] - 0s 47us/step - loss: 0.6939 - acc: 0.6748 - mean_squared_error: 0.1315
Epoch 127/1000
984/984 [==============================] - 0s 52us/step - loss: 0.6923 - acc: 0.6900 - mean_squared_error: 0.1311
Epoch 128/1000
984/984 [==============================] - 0s 71us/step - loss: 0.6957 - acc: 0.6819 - mean_squared_error: 0.1317
Epoch 129/1000
984/984 [==============================] - 0s 46us/step - loss: 0.6899 - acc: 0.6809 - mean_squar

984/984 [==============================] - 0s 37us/step - loss: 0.6600 - acc: 0.6911 - mean_squared_error: 0.1259
Epoch 186/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6574 - acc: 0.6911 - mean_squared_error: 0.1255
Epoch 187/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6580 - acc: 0.6890 - mean_squared_error: 0.1256
Epoch 188/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6563 - acc: 0.6799 - mean_squared_error: 0.1253
Epoch 189/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6558 - acc: 0.6951 - mean_squared_error: 0.1251
Epoch 190/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6571 - acc: 0.6850 - mean_squared_error: 0.1255
Epoch 191/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6584 - acc: 0.6921 - mean_squared_error: 0.1258
Epoch 192/1000
984/984 [==============================] - 0s 39us/step - loss: 0.6559 - acc: 0.6911 - mean_squar

984/984 [==============================] - 0s 34us/step - loss: 0.6393 - acc: 0.6931 - mean_squared_error: 0.1228
Epoch 249/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6392 - acc: 0.6982 - mean_squared_error: 0.1224
Epoch 250/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6401 - acc: 0.6992 - mean_squared_error: 0.1226
Epoch 251/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6382 - acc: 0.7033 - mean_squared_error: 0.1224
Epoch 252/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6401 - acc: 0.7063 - mean_squared_error: 0.1226
Epoch 253/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6384 - acc: 0.7043 - mean_squared_error: 0.1223
Epoch 254/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6387 - acc: 0.7022 - mean_squared_error: 0.1224
Epoch 255/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6407 - acc: 0.6941 - mean_squar

984/984 [==============================] - 0s 38us/step - loss: 0.6350 - acc: 0.7053 - mean_squared_error: 0.1220
Epoch 312/1000
984/984 [==============================] - 0s 42us/step - loss: 0.6353 - acc: 0.7043 - mean_squared_error: 0.1221
Epoch 313/1000
984/984 [==============================] - 0s 41us/step - loss: 0.6350 - acc: 0.6972 - mean_squared_error: 0.1222
Epoch 314/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6373 - acc: 0.6900 - mean_squared_error: 0.1229
Epoch 315/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6371 - acc: 0.6951 - mean_squared_error: 0.1223
Epoch 316/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6345 - acc: 0.7012 - mean_squared_error: 0.1220
Epoch 317/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6343 - acc: 0.7012 - mean_squared_error: 0.1220
Epoch 318/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6346 - acc: 0.7043 - mean_squar

984/984 [==============================] - 0s 37us/step - loss: 0.6329 - acc: 0.7022 - mean_squared_error: 0.1220
Epoch 375/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6361 - acc: 0.7033 - mean_squared_error: 0.1226
Epoch 376/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6352 - acc: 0.7002 - mean_squared_error: 0.1223
Epoch 377/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6335 - acc: 0.7012 - mean_squared_error: 0.1219
Epoch 378/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6339 - acc: 0.6992 - mean_squared_error: 0.1220
Epoch 379/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6363 - acc: 0.6972 - mean_squared_error: 0.1225
Epoch 380/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6337 - acc: 0.7022 - mean_squared_error: 0.1220
Epoch 381/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6329 - acc: 0.7002 - mean_squar

984/984 [==============================] - 0s 38us/step - loss: 0.6342 - acc: 0.7063 - mean_squared_error: 0.1221
Epoch 438/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6323 - acc: 0.7043 - mean_squared_error: 0.1218
Epoch 439/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6333 - acc: 0.7053 - mean_squared_error: 0.1218
Epoch 440/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6320 - acc: 0.7114 - mean_squared_error: 0.1216
Epoch 441/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6316 - acc: 0.7012 - mean_squared_error: 0.1216
Epoch 442/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6342 - acc: 0.7053 - mean_squared_error: 0.1223
Epoch 443/1000
984/984 [==============================] - 0s 48us/step - loss: 0.6367 - acc: 0.7012 - mean_squared_error: 0.1222
Epoch 444/1000
984/984 [==============================] - 0s 49us/step - loss: 0.6339 - acc: 0.7002 - mean_squar

984/984 [==============================] - 0s 39us/step - loss: 0.6316 - acc: 0.7073 - mean_squared_error: 0.1217
Epoch 501/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6313 - acc: 0.7022 - mean_squared_error: 0.1216
Epoch 502/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6314 - acc: 0.7043 - mean_squared_error: 0.1216
Epoch 503/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6309 - acc: 0.7012 - mean_squared_error: 0.1215
Epoch 504/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6322 - acc: 0.7083 - mean_squared_error: 0.1218
Epoch 505/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6328 - acc: 0.7033 - mean_squared_error: 0.1220
Epoch 506/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6336 - acc: 0.7043 - mean_squared_error: 0.1218
Epoch 507/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6321 - acc: 0.7033 - mean_squar

984/984 [==============================] - 0s 37us/step - loss: 0.6324 - acc: 0.6972 - mean_squared_error: 0.1217
Epoch 564/1000
984/984 [==============================] - 0s 41us/step - loss: 0.6303 - acc: 0.7073 - mean_squared_error: 0.1215
Epoch 565/1000
984/984 [==============================] - 0s 39us/step - loss: 0.6309 - acc: 0.7063 - mean_squared_error: 0.1215
Epoch 566/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6316 - acc: 0.7053 - mean_squared_error: 0.1217
Epoch 567/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6309 - acc: 0.7012 - mean_squared_error: 0.1214
Epoch 568/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6316 - acc: 0.7033 - mean_squared_error: 0.1218
Epoch 569/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6316 - acc: 0.7033 - mean_squared_error: 0.1216
Epoch 570/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6316 - acc: 0.7012 - mean_squar

984/984 [==============================] - 0s 40us/step - loss: 0.6309 - acc: 0.7012 - mean_squared_error: 0.1216
Epoch 627/1000
984/984 [==============================] - 0s 39us/step - loss: 0.6299 - acc: 0.7012 - mean_squared_error: 0.1214
Epoch 628/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6323 - acc: 0.7033 - mean_squared_error: 0.1218
Epoch 629/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6313 - acc: 0.7002 - mean_squared_error: 0.1216
Epoch 630/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6301 - acc: 0.7043 - mean_squared_error: 0.1214
Epoch 631/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6315 - acc: 0.7022 - mean_squared_error: 0.1217
Epoch 632/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6305 - acc: 0.7012 - mean_squared_error: 0.1216
Epoch 633/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6300 - acc: 0.7063 - mean_squar

984/984 [==============================] - 0s 33us/step - loss: 0.6307 - acc: 0.7033 - mean_squared_error: 0.1216
Epoch 690/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6341 - acc: 0.7033 - mean_squared_error: 0.1224
Epoch 691/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6326 - acc: 0.7043 - mean_squared_error: 0.1220
Epoch 692/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6303 - acc: 0.7043 - mean_squared_error: 0.1215
Epoch 693/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6303 - acc: 0.7083 - mean_squared_error: 0.1215
Epoch 694/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6321 - acc: 0.7022 - mean_squared_error: 0.1218
Epoch 695/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6308 - acc: 0.7022 - mean_squared_error: 0.1218
Epoch 696/1000
984/984 [==============================] - 0s 47us/step - loss: 0.6321 - acc: 0.7043 - mean_squar

984/984 [==============================] - 0s 39us/step - loss: 0.6298 - acc: 0.7043 - mean_squared_error: 0.1216
Epoch 753/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6304 - acc: 0.7022 - mean_squared_error: 0.1215
Epoch 754/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6300 - acc: 0.7063 - mean_squared_error: 0.1215
Epoch 755/1000
984/984 [==============================] - 0s 39us/step - loss: 0.6298 - acc: 0.7104 - mean_squared_error: 0.1214
Epoch 756/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6300 - acc: 0.7073 - mean_squared_error: 0.1215
Epoch 757/1000
984/984 [==============================] - 0s 41us/step - loss: 0.6305 - acc: 0.7043 - mean_squared_error: 0.1214
Epoch 758/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6328 - acc: 0.6921 - mean_squared_error: 0.1221
Epoch 759/1000
984/984 [==============================] - 0s 38us/step - loss: 0.6325 - acc: 0.6961 - mean_squar

984/984 [==============================] - 0s 38us/step - loss: 0.6297 - acc: 0.7053 - mean_squared_error: 0.1215
Epoch 816/1000
984/984 [==============================] - 0s 53us/step - loss: 0.6303 - acc: 0.7033 - mean_squared_error: 0.1216
Epoch 817/1000
984/984 [==============================] - 0s 63us/step - loss: 0.6317 - acc: 0.7043 - mean_squared_error: 0.1219
Epoch 818/1000
984/984 [==============================] - 0s 78us/step - loss: 0.6295 - acc: 0.7063 - mean_squared_error: 0.1214
Epoch 819/1000
984/984 [==============================] - 0s 55us/step - loss: 0.6302 - acc: 0.7053 - mean_squared_error: 0.1216
Epoch 820/1000
984/984 [==============================] - 0s 54us/step - loss: 0.6304 - acc: 0.7063 - mean_squared_error: 0.1215
Epoch 821/1000
984/984 [==============================] - 0s 70us/step - loss: 0.6302 - acc: 0.7073 - mean_squared_error: 0.1216
Epoch 822/1000
984/984 [==============================] - 0s 40us/step - loss: 0.6302 - acc: 0.7083 - mean_squar

984/984 [==============================] - 0s 34us/step - loss: 0.6293 - acc: 0.7083 - mean_squared_error: 0.1214
Epoch 879/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6333 - acc: 0.7002 - mean_squared_error: 0.1219
Epoch 880/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6298 - acc: 0.7083 - mean_squared_error: 0.1214
Epoch 881/1000
984/984 [==============================] - 0s 36us/step - loss: 0.6304 - acc: 0.7033 - mean_squared_error: 0.1216
Epoch 882/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6317 - acc: 0.6992 - mean_squared_error: 0.1221
Epoch 883/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6296 - acc: 0.7043 - mean_squared_error: 0.1215
Epoch 884/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6308 - acc: 0.7033 - mean_squared_error: 0.1218
Epoch 885/1000
984/984 [==============================] - 0s 35us/step - loss: 0.6297 - acc: 0.7093 - mean_squar

984/984 [==============================] - 0s 36us/step - loss: 0.6298 - acc: 0.7053 - mean_squared_error: 0.1214
Epoch 942/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6306 - acc: 0.7043 - mean_squared_error: 0.1217
Epoch 943/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6303 - acc: 0.7063 - mean_squared_error: 0.1214
Epoch 944/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6300 - acc: 0.7083 - mean_squared_error: 0.1215
Epoch 945/1000
984/984 [==============================] - 0s 33us/step - loss: 0.6303 - acc: 0.7083 - mean_squared_error: 0.1216
Epoch 946/1000
984/984 [==============================] - 0s 34us/step - loss: 0.6298 - acc: 0.7033 - mean_squared_error: 0.1213
Epoch 947/1000
984/984 [==============================] - 0s 37us/step - loss: 0.6311 - acc: 0.7053 - mean_squared_error: 0.1216
Epoch 948/1000
984/984 [==============================] - 0s 43us/step - loss: 0.6299 - acc: 0.7053 - mean_squar

NameError: name 'plt' is not defined

In [39]:
score = model.evaluate(X_train, y_train)
print("train score: {}".format(score))
score = model.evaluate(X_test, y_test)
print("test score: {}".format(score))

984/984 [==============================] - 0s 94us/step
train score: [0.63186635137573488, 0.70833333381792396, 0.12173008300909181]
329/329 [==============================] - 0s 30us/step
test score: [0.63738980943671109, 0.71124620097024105, 0.12284303694329363]


In [100]:
y_pred=model.predict(X_test)
print("Raw softmax (rows should sum to 1):\n",y_pred[0:5])
y_pred = (y_pred > 0.4)
print("\nDecision boundary at 0.4:\n",y_pred[0:5])
y_args = np.argmax(y_pred, axis=1)
print("\nIndices of maxima:\n", y_args[0:5])

Raw softmax (rows should sum to 1):
 [[ 0.58853662  0.32071784  0.09074555]
 [ 0.26768655  0.41721183  0.31510162]
 [ 0.12132533  0.36609969  0.51257503]
 [ 0.57113326  0.33015537  0.09871134]
 [ 0.02655725  0.0297599   0.94368285]]

Decision boundary at 0.4:
 [[ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]]

Indices of maxima:
 [0 1 2 0 2]


In [101]:
from sklearn import metrics
def measure_performance(X,y,clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred=clf.predict(X)
    
    y = np.argmax(np.array(y), axis=1)
    y_pred = np.argmax(y_pred, axis=1)

    if show_accuracy:
        print( "Accuracy:{0:.3f}".format(metrics.accuracy_score(y,y_pred)),"\n")

    if show_classification_report:
        print( "Classification report")
        print( metrics.classification_report(y,y_pred),"\n")
        
    if show_confusion_matrix:
        print( "Confusion matrix")
        print( metrics.confusion_matrix(y,y_pred),"\n")

In [102]:
measure_performance(X_test, y_test, model, show_accuracy=True)

Accuracy:0.711 

Classification report
             precision    recall  f1-score   support

          0       0.61      0.57      0.59        80
          1       0.52      0.56      0.54        79
          2       0.85      0.85      0.85       170

avg / total       0.71      0.71      0.71       329
 

Confusion matrix
[[ 46  27   7]
 [ 16  44  19]
 [ 13  13 144]] 

